# To get started with security, check out the documentation:
# https://symfony.com/doc/current/book/security.html
security:
    encoders:
        Application\Sonata\UserBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: true
            iterations: 2

    acl:
        connection: default

    role_hierarchy:
        ROLE_VENDEUR:     [ROLE_USER]
        ROLE_BOUTIQUE:    [ROLE_USER]
        ROLE_DR:          [ROLE_USER]
        ROLE_MARQUE:      [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            # if you are not using acl then this line must be uncommented
            #- ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT
            #- ROLE_SONATA_PAGE_ADMIN_BLOCK_EDIT

    providers:
        fos_userbundle:
            id: fos_user.user_manager
            #id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                default_target_path: /admin
            logout:
                path:           /admin/logout
                target:         /admin/login
            anonymous:          true
            switch_user:        true

        main:
            pattern:             /
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
                default_target_path: /
            logout:             true
            anonymous:          true
            switch_user:        true

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        #- { path: ^/.*, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/register, role: ROLE_ADMIN , requires_channel: https }
        - { path: ^/resetting, role: ROLE_ADMIN, requires_channel: https }
        - { path: ^/web/config.php, role: ROLE_ADMIN , requires_channel: https }
        #- { path: ^/profile/edit-profile, role: ROLE_ADMIN , requires_channel: https }
        #- { path: ^/profile, role: ROLE_ADMIN , requires_channel: https }
        - { path: ^/kpi/, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        # Admin login page needs to be accessed without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        # App URLs
        - { path: ^/home$, role: ROLE_USER, requires_channel: https }
        - { path: ^/test$, role: ROLE_USER, requires_channel: https }
        - { path: ^/campaign$, role: ROLE_USER, requires_channel: https }
        - { path: ^/campaign/, role: ROLE_USER, requires_channel: https }
        - { path: ^/campaign_send_email/, role: ROLE_USER, requires_channel: https }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN], requires_channel: https }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
