<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CampaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignFileRepository extends \Doctrine\ORM\EntityRepository
{
	public function getCampaignOfMonth($date1, $date2, $brand)
	{
		$qb = $this->createQueryBuilder('c')
			->where('c.date BETWEEN :date1 and :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('c.brand = :brand')
		  	->setParameter('brand', $brand)
		;

		return $qb
			->getQuery()
			->getOneOrNullResult()
		;
	} 
}
