<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Application\Sonata\UserBundle\Entity\User;

/**
 * KpiMonthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KpiMonthRepository extends EntityRepository
{
	public function getUserKpisBetweenDates(User $user, $date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.user = :user')
		  	->setParameter('user', $user)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->orderBy('k.date', 'DESC')
		;

		return $qb
			->getQuery()
			->getResult();
	}

	public function getTop3Ca($brand, $date){
		$qb = $this
			->createQueryBuilder('k')
		  	->orderBy('k.caClientsTransformesM0', 'DESC')
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->where('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('u.role = :role')
		  	->andWhere('k.date = :date')
		  	->andWhere('u.ispremium != 1')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setParameter('date', $date)
		  	->setMaxResults(3);
		;

		return $qb
			->getQuery()
			->getResult();
	}

	/*********************************************************/

	public function getRank1Npe($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpeM0 = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1Npes($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpesM0 = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1Npesa($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpesaM0 = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	/*********************************************************/

	public function getRank1NpeVendeur($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpeM0 = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1NpesVendeur($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpesM0 = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1NpesaVendeur($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpesaM0 = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	/*********************************************************/

	public function getRank1NpeYtd($date1,$date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpeYtd = 1')
			//->setParameter('val', 1)
			->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1NpesYtd($date1,$date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpesYtd= 1')
			//->setParameter('val', 1)
			->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1NpesaYtd($date1,$date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpesaYtd = 1')
			//->setParameter('val', 1)
			->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')		  	
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	/*********************************************************/



	public function getRank1NpeYtdVendeur($date1,$date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpesaYtd = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}


	public function getRank1NpesYtdVendeur($date1,$date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpesaYtd = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1NpesaYtdVendeur($date1,$date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpesaYtd = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	/*********************************************************/

	public function getRank1Npe2($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpe2M0 = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1Nps2($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNps2M0 = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1Npes2($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpes2M0 = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	/*********************************************************/

	public function getRank1Npe2Vendeur($date1, $date2, $brand, $boutique){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpe2M0 = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('u.boutique = :boutique')
		  	->setParameter('boutique', $boutique)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1Nps2Vendeur($date1, $date2, $brand, $boutique){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNps2M0 = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('u.boutique = :boutique')
		  	->setParameter('boutique', $boutique)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1Npes2Vendeur($date1, $date2, $brand, $boutique){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpes2M0 = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('u.boutique = :boutique')
		  	->setParameter('boutique', $boutique)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	/*********************************************************/

	public function getRank1Npe2Ytd($date1,$date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpe2Ytd = 1')
			//->setParameter('val', 1)
			->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1Nps2Ytd($date1,$date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNps2Ytd= 1')
			//->setParameter('val', 1)
			->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1Npes2Ytd($date1,$date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpes2Ytd = 1')
			//->setParameter('val', 1)
			->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')		  	
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	/*********************************************************/



	public function getRank1Npe2YtdVendeur($date1,$date2, $brand, $boutique){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpe2Ytd = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('u.boutique = :boutique')
		  	->setParameter('boutique', $boutique)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}


	public function getRank1Nps2YtdVendeur($date1,$date2, $brand, $boutique){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNps2Ytd = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('u.boutique = :boutique')
		  	->setParameter('boutique', $boutique)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1Npes2YtdVendeur($date1,$date2, $brand, $boutique){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpes2Ytd = 1')
			//->setParameter('val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('u.boutique = :boutique')
		  	->setParameter('boutique', $boutique)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	/*********************************************************/


	public function getKpiVendeurBoutique($boutique, $date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
			->where('u.boutique = :boutique')
		  	->setParameter('boutique', $boutique)
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->orderBy('u.username', 'ASC')
		;

		return $qb
			->getQuery()
			->getResult();
	}

	/*********************************************************/

	public function getRank1_3NPS($date1,$date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->where('u.brand = :brand')		  	
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->orderBy('k.questsatisfranknpsytd', 'ASC')
		  	->setMaxResults(3);
		;

		return $qb
			->getQuery()
			->getResult();
	}


	public function getKpiBoutiqueDr($dr, $date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
			->where('u.dr = :dr')
		  	->setParameter('dr', $dr)
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->orderBy('u.username', 'ASC')
		;

		return $qb
			->getQuery()
			->getResult();
	}


	public function getKpiDrMarque($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
			->where('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_DR")
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->orderBy('u.username', 'ASC')
		;

		return $qb
			->getQuery()
			->getResult();
	}


	public function getKpiMarque($date1, $date2, $username){
		$qb = $this
			->createQueryBuilder('k')
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
			->where('u.username = :username')
		  	->setParameter('username', $username)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_MARQUE")
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->orderBy('u.username', 'ASC')
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
			//->getResult();
	}

	/***********************************************/

	public function getKpisMarque($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->select('k.id')
		  	->leftJoin('k.user', 'u')
			->where('u.brand = :brand or u.username = :brand')
		  	->setParameter('brand', $brand)
		  	//->andWhere('u.role = :role')
		  	//->setParameter('role', "ROLE_MARQUE")
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->orderBy('u.role', 'ASC')
		;

		return $qb
			->getQuery()
			->getResult();
	}


	public function getKpisBoutique($date1, $date2, $boutique, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->select('k.id')
		  	->leftJoin('k.user', 'u')
			->where('u.boutique = :boutique or u.boutique = :boutique or u.username = :brand')
		  	->setParameter('boutique', $boutique)
		  	->setParameter('brand', $brand)
		  	//->andWhere('u.role = :role')
		  	//->setParameter('role', "ROLE_MARQUE")
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->orderBy('u.role', 'ASC')
		;

		return $qb
			->getQuery()
			->getResult();
	}


	public function getKpisDr($date1, $date2, $dr, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->select('k.id')
		  	->leftJoin('k.user', 'u')
			->where('u.dr = :dr or u.username = :dr or u.username = :brand')
		  	->setParameter('dr', $dr)
		  	->setParameter('brand', $brand)
		  	//->andWhere('u.role = :role')
		  	//->setParameter('role', "ROLE_MARQUE")
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->orderBy('u.role', 'ASC')
		;

		return $qb
			->getQuery()
			->getResult();
	}
}
