<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Application\Sonata\UserBundle\Entity\User;

/**
 * KpiMonthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KpiWeekRepository extends EntityRepository
{
	public function getUserKpisBetweenDates(User $user, $date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.user = :user')
		  	->setParameter('user', $user)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->orderBy('k.date', 'DESC')
		;

		return $qb
			->getQuery()
			->getResult();
	}

	/*********************************************************/

	public function getRank1_3NPS($date1,$date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->where('u.brand = :brand')		  	
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->orderBy('k.questsatisfranknpsytd', 'ASC')
		  	->setMaxResults(3);
		;

		return $qb
			->getQuery()
			->getResult();
	}

	/*********************************************************/

	public function getRank1Npe($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpeS0 = :val')
			->setParameter(':val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1Npes($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpesS0= :val')
			->setParameter(':val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1Npesa($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpesaS0 = :val')
			->setParameter(':val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	/*********************************************************/

	public function getRank1NpeVendeur($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpeS0 = :val')
			->setParameter(':val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1NpesVendeur($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpesS0= :val')
			->setParameter(':val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1NpesaVendeur($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpesaS0 = :val')
			->setParameter(':val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	/*****************************************************/

	public function getRank1Npe2($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpe2S0 = :val')
			->setParameter(':val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1Nps2($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNps2S0= :val')
			->setParameter(':val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1Npes2($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpes2S0 = :val')
			->setParameter(':val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	/*********************************************************/

	public function getRank1Npe2Vendeur($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpe2S0 = :val')
			->setParameter(':val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1Nps2Vendeur($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNps2S0= :val')
			->setParameter(':val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	public function getRank1Npes2Vendeur($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
			->where('k.rankNpes2S0 = :val')
			->setParameter(':val', 1)
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->setMaxResults(1);
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
	}

	/*********************************************************/


	public function getKpiVendeurBoutique($boutique, $date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
			->where('u.boutique = :boutique')
		  	->setParameter('boutique', $boutique)
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_VENDEUR")
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->orderBy('u.username', 'ASC')
		;

		return $qb
			->getQuery()
			->getResult();
	}


	public function getKpiBoutiqueDr($dr, $date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
			->where('u.dr = :dr')
		  	->setParameter('dr', $dr)
		  	->andWhere('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_BOUTIQUE")
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->orderBy('u.username', 'ASC')
		;

		return $qb
			->getQuery()
			->getResult();
	}


	public function getKpiDrMarque($date1, $date2, $brand){
		$qb = $this
			->createQueryBuilder('k')
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
			->where('u.brand = :brand')
		  	->setParameter('brand', $brand)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_DR")
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->orderBy('u.username', 'ASC')
		;

		return $qb
			->getQuery()
			->getResult();
	}


	public function getKpiMarque($date1, $date2, $username){
		$qb = $this
			->createQueryBuilder('k')
		  	->leftJoin('k.user', 'u')
		  	->addSelect('u')
			->where('u.username = :username')
		  	->setParameter('username', $username)
		  	->andWhere('u.role = :role')
		  	->setParameter('role', "ROLE_MARQUE")
		  	->andWhere('k.date BETWEEN :date1 AND :date2')
		  	->setParameter('date1', $date1)
		  	->setParameter('date2', $date2)
		  	->orderBy('u.username', 'ASC')
		;

		return $qb
			->getQuery()
			->getOneOrNullResult();
			//->getResult();
	}
}
